server:
  port: 0

spring:
  datasource:
    url: jdbc:postgresql://localhost:5433/order_db
    username: dbuser
    password: 12345
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
  cloud:
    openfeign:
      circuitbreaker:
        enabled: true
        # Без этой строки Feign будет просто пытаться соединиться,
        # падать с ошибкой и всё. С этой строкой Spring Cloud автоматически оборачивает
        # каждый метод @FeignClient в прокси, который следит за ошибками.
        # Если ошибок становится много - прокси сам не даст сделать новый вызов,
        # а сразу выбросит исключение (состояние OPEN).

feign:
  client:
    config:
      default:   # применяется по умолчанию для всех клиентов
        connectTimeout: 2000
        readTimeout: 3000
      product-service:
        loggerLevel: basic
      inventory-service:  # название сервиса в @FeignClient
        connectTimeout: 1000
        readTimeout: 2000

resilience4j:
  circuitbreaker:
    configs:
      default:
        sliding-window-size: 5
        # "Скользящее окно" из 5 последних вызовов. Resilience4j смотрит только на них
        # Старые успешные вызовы выпадают из истории, новые добавляются
        failure-rate-threshold: 50
        # Порог срабатывания: если в этих 5 последних вызовах 50% (то есть 3 из 5) были ошибками -
        # цепь (Circuit Breaker) переходит в состояние OPEN.
        wait-duration-in-open-state: 10s
        # Сколько времени цепь будет оставаться в состоянии OPEN (отсекать все запросы).
        # Даже если сервис уже поднялся, следующие 10 секунд новые вызовы не пойдут.
        permitted-number-of-calls-in-half-open-state: 3
        # После истечения 10 секунд цепь переходит в состояние HALF_OPEN.
        # Разрешается сделать только 3 пробных вызова.
        # Если они успешны - цепь закрывается (CLOSED), и всё работает как обычно.
        # Если хоть один падает - цепь снова уходит в OPEN ещё на 10 секунд.
  timelimiter:
    configs:
      default:
        timeout-duration: 3s
        # Таймаут на один конкретный вызов. Даже если сервер думает 2 минуты,
        # через 3 секунды Feign принудительно оборвёт соединение и выбросит ошибку.
        # Эта ошибка (TimeoutException) считается "технической", попадает под Circuit Breaker
        # и активирует fallback-код

logging:
  level:
    ru.yandex.practicum.order.feign: DEBUG