kafka:
  bootstrap-servers: localhost:9092
  consumer:
    group-id: aggregator-service
  topics:
    sensors: telemetry.sensors.v1
    snapshots: telemetry.snapshots.v1

spring:
  application:
    name: aggregator