# Тут хранятся настройки, которые относятся ко всей системе Smart Home Tech
# или могут переиспользоваться несколькими подсистемами

spring:
  main:
    banner-mode: off
    log-startup-info: false

logging:
  level:
    ru.yandex.practicum.telemetry: WARN
    org:
      springframework: ERROR
      apache.kafka: WARN

kafka:
  bootstrap-servers: "localhost:9092"